#!/usr/bin/env bash
#
# Builds a signed, installable release APK.
#
# `android/` is generated by `expo prebuild` and is not committed, so the
# signing configuration cannot live inside it — this script regenerates the
# project and injects the signing settings each time, which keeps the build
# reproducible from a clean checkout.
#
# Usage:  ./scripts/build-apk.sh
# Output: dist/sift-release.apk
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

KEYSTORE_DIR="$ROOT/credentials"
KEYSTORE="$KEYSTORE_DIR/sift-release.keystore"
KEY_ALIAS="sift"
# Demonstration credentials. A real release would keep these out of the repo
# and supply them from the environment or a secret store.
STORE_PASSWORD="${SIFT_KEYSTORE_PASSWORD:-siftrelease}"

if [ ! -f "$KEYSTORE" ]; then
  echo "==> Generating a release keystore (first run only)"
  mkdir -p "$KEYSTORE_DIR"
  keytool -genkeypair -v \
    -keystore "$KEYSTORE" \
    -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass "$STORE_PASSWORD" -keypass "$STORE_PASSWORD" \
    -dname "CN=Sift, OU=Mobile Applications, O=Villa College, L=Male, C=MV"
fi

echo "==> Generating the native project"
npx expo prebuild --platform android --no-install

echo "==> Injecting signing configuration"
cat >> android/gradle.properties <<PROPS

# Injected by scripts/build-apk.sh
SIFT_UPLOAD_STORE_FILE=$KEYSTORE
SIFT_UPLOAD_KEY_ALIAS=$KEY_ALIAS
SIFT_UPLOAD_STORE_PASSWORD=$STORE_PASSWORD
SIFT_UPLOAD_KEY_PASSWORD=$STORE_PASSWORD
PROPS

# Point the release build at the upload key instead of the debug key that the
# React Native template uses by default.
python3 - <<'PY'
import re, pathlib
path = pathlib.Path('android/app/build.gradle')
text = path.read_text()

signing = '''        release {
            storeFile file(SIFT_UPLOAD_STORE_FILE)
            storePassword SIFT_UPLOAD_STORE_PASSWORD
            keyAlias SIFT_UPLOAD_KEY_ALIAS
            keyPassword SIFT_UPLOAD_KEY_PASSWORD
        }
'''
text = re.sub(r'(signingConfigs \{\n)', r'\1' + signing, text, count=1)
text = text.replace('signingConfig signingConfigs.debug\n            shrinkResources',
                    'signingConfig signingConfigs.release\n            shrinkResources')
text = re.sub(r'(buildTypes \{[\s\S]*?release \{[\s\S]*?)signingConfig signingConfigs\.debug',
              r'\1signingConfig signingConfigs.release', text, count=1)
path.write_text(text)
print('signing config applied')
PY

echo "==> Building release APK"
(cd android && ./gradlew assembleRelease --no-daemon)

mkdir -p dist
cp android/app/build/outputs/apk/release/app-release.apk dist/sift-release.apk
echo
echo "==> Built dist/sift-release.apk"
ls -lh dist/sift-release.apk
